sudo: required

install:
  - sudo apt-get update
  - sudo apt-get install expect
  - npm install -g particle-cli

before_script:
  - ./particle-cli-login.sh $EMAIL $PASS

script:
  - make build

deploy:
  provider: script
  skip_cleanup: true
  script: make flash
  on:
    branch: master